version: "3.1"

services:
  db:
    image: jogurat/db-test
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/postgres/data
    ports:
      - 1112:5432
    volumes:
      - mydb:/var/postgres/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 1111:8080

  node:
    image: jogurat/spatula-node

  spatula:
    image: jogurat/spatula:1.0
    environment:
      NODE_URL: ${NODE_URL}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 1313:3000
    depends_on:
      - "db"

  vue:
    image: jogurat/spatula-vue
    ports:
      - 8080:8080

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 1414:8080
    environment:
      URL: /swagger.yml

volumes:
  mydb:
